package beakid

import "math/bits"

// BeakId is a unique 64-bit identifier produced by Generator.
//
// BeakId values are naturally ordered — IDs generated by the same Generator
// on the same goroutine are strictly increasing, so sorting a slice of BeakIds
// recovers approximate creation order.
type BeakId uint64

// New wraps a raw uint64 as a BeakId.
// Intended for deserialization or reconstruction from storage.
func New(v uint64) BeakId {
	return BeakId(v)
}

const (
	base62Len      = 11
	base62Alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
)

// FromBase62 decodes a BeakId from an 11-character base62 string.
//
// Alphabet: 0–9, A–Z, a–z (digits first, then uppercase, then lowercase).
//
// Returns ErrInvalidBase62 if the string length is not exactly 11,
// contains a character outside the alphabet, or the value overflows uint64.
func FromBase62(s string) (BeakId, error) {
	if len(s) != base62Len {
		return 0, ErrInvalidBase62
	}

	var n uint64
	for i := 0; i < len(s); i++ {
		b := s[i]
		var digit uint64
		switch {
		case b >= '0' && b <= '9':
			digit = uint64(b - '0')
		case b >= 'A' && b <= 'Z':
			digit = uint64(b-'A') + 10
		case b >= 'a' && b <= 'z':
			digit = uint64(b-'a') + 36
		default:
			return 0, ErrInvalidBase62
		}

		hi, lo := bits.Mul64(n, 62)
		if hi != 0 {
			return 0, ErrInvalidBase62
		}
		sum := lo + digit
		if sum < lo {
			return 0, ErrInvalidBase62
		}
		n = sum
	}

	return BeakId(n), nil
}

// Base62 encodes the ID as an 11-character base62 string.
//
// The output is always exactly 11 characters, left-padded with '0' for small
// values. Reversible via FromBase62.
func (b BeakId) Base62() string {
	var buf [base62Len]byte
	n := uint64(b)
	for i := base62Len - 1; i >= 0; i-- {
		buf[i] = base62Alphabet[n%62]
		n /= 62
	}
	return string(buf[:])
}
